### ISSUE TITLE
Uint64 values out of range

### ISSUE THREAD

**Issue by jonyoder** [aquasecurity/go-pep440-version#1]
I was testing the version parsing against all current PyPI.org versions, and I ran into some out-of-range version components that are allowed by PyPI.org:

```
error parsing version: strconv.ParseUint: parsing "20210609131134657401": value out of range
error parsing version: strconv.ParseUint: parsing "9786796767868973145897342348293748973489579438579384579384": value out of range
error parsing version: strconv.ParseUint: parsing "14159265358979323846264338327950288419716939937510582097494459230781640628620899862803482534211706798214808651328230664709384460955058223172535940812848111745028410270193852110555964462294895493038196442881097566593": value out of range
```

I have a working fix that modifies `part.Uint64` to use `math/big` instead of `uint64`, and it fixes the issue. These changes are on a fork in our codebase.

Would you be interested in these improvements? If so, I can create a pull request here and also in the related `aquasecurity/go-version` module. Obviously, I would also change the modifications in `go-version` to add a new part type instead of modifying `part.Uint64`.

**Comment by jeffwidman** [comment]
@jonyoder can you please create the PR? 

I'm not the maintainer of this library, but as someone who _does_ maintain open source libraries, the answer is invariably "yes, please" whenever someone offers to provide a small straightforward bugfix pr that includes tests.

**Comment by jeffwidman** [comment]
Also, if you don't have time, let me know as I'd like to see the bug fixed, so I can put up a PR... but don't want to take credit from you if you've already got a fix available, you go for it! 👍

**Comment by jonyoder** [comment]
@jeffwidman Thanks for the nudge, and apologies for the long silence.

Please go ahead. I don't have the patch anymore. We ended up needing PEP 508 markers, extras and wheel tags alongside PEP 440, so we wrote our own primitives ([posit-dev/go-python-packaging](https://github.com/posit-dev/go-python-packaging)) rather than carry a fork. Nothing to take credit for on my side.

The bug is still live, for what it's worth: `part.Uint64` in `aquasecurity/go-version` is still a plain `uint64` parsed with `strconv.ParseUint`, so the versions above still fail to parse.

Two things I'd want to know before spending time on it, though.

The fix mostly lives in `aquasecurity/go-version` rather than here, and that repo has been quiet since December 2024. Its only tag is `v0.0.1`, and Trivy depends on that tag rather than on a commit, so even a merged fix wouldn't reach anyone until someone cut a new one. Probably worth asking a maintainer about tagging before you write the code.

On the code itself: adding a new big-integer part type is easier than changing `Uint64`, since `const Zero = Uint64(0)` has to stay a constant. The catch is comparison. Each part type's `Compare` switches on the other part's concrete type and quietly returns 0 for anything it doesn't handle, so a new type you forget to add a case for compares *equal* instead of greater, with no error to tell you. That's most of the work. Keeping anything that fits in a `uint64` on the existing path limits how much you have to touch.

Want me to drop that into a file somewhere durable, or post it to the issue for you?
